version: '3.8'
services:
  app:
    image: golang:1.23
    working_dir: /app
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=postgres://user:password@postgres:5432/kvstore?sslmode=disable
    volumes:
      - .:/app
    command: sh -c "go mod download && go run main.go redis.go db.go handlers.go"
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=kvstore
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"